K equavalence test
ElectricCoffee/P7-Code pull request #4
Opened 2017-10-30 12:31 UTC by mortenm12

2017-10-30 12:51 UTC, Stig9999 requested changes
Imports skal standardiseres, clock_names og name skal fjernes fra Context, kommentar til test cases.

2017-10-30 13:30 UTC, Stig9999 approved these changes

2017-10-30 13:33 UTC, Luraman approved these changes

2017-10-31 07:51 UTC, ElectricCoffee requested changes
Fiks kommentar, så er det i orden

2017-10-31 07:57 UTC, ElectricCoffee approved these changes

2017-10-31 07:59 UTC, merged